public class ListDemo {
    public static void candidatesList(integer i) {
        List<String>  listCandidate = new List<String>();
        listCandidate.add('Marc');
        listCandidate.add('Elon');
        listCandidate.add('Bill');
        listCandidate.add('Marc');
        string indexValue1= listCandidate[i];
        System.debug('Candidates are ' + listCandidate);
        system.debug(indexValue1);
        
    }
    public static void randomIntegerList () {
        List<Integer>  listInteger = new List<Integer>();
        listInteger.add(10);
        listInteger.add(15);
        listInteger.add(21);
        listInteger.add(15);
        listInteger.add(15);
        listInteger.add(15);
        Integer indexValue = listInteger[3];

        system.debug(listInteger);
        system.debug(indexValue);

    }
    public static  allCats() {
        List<cat> cats = new List<cat>();
        cat falconscat = new cat ('flufykins' ,  'White');
        cat imaneCat = new cat('Simba', 'Brown');
        cat salimCat = new cat('Smokey' , 'Gray');

        catS.add
    }
}
