Map<string, String> zipCodeMap = new Map<String,String>();
zipCodeMap.put('11102', 'Ahmadabad');
zipCodeMap.put('312344', 'Delhi');
zipCodeMap.put('123445', 'California');
zipCodeMap.put('9876754', 'California');
system.debug(zipCodeMap);

Map<integer, string> m2 = new Map<integer, string>();
m2.put(1, 'arg1');
Map<string, integer> m3= new Map<string, integer>();
m3.put('imane', 3);
system.debug(m2);
system.debug(m3);